# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(900, 600)
        LoginForm.setLayoutDirection(QtCore.Qt.LeftToRight)
        LoginForm.setStyleSheet("QWidget#wtTitle QLabel {\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"    color: #fff; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtBackground {\n"
"    border-image: url(:/images/icons/login/119254-abstract-bright-blue-background-graphic-design.jpg);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QWidget#wtBackgroundBlur {\n"
"   background-color: rgba(30, 30, 30, 30);\n"
"}\n"
"\n"
"QWidget#wtForm {\n"
"    border-radius: 16px;\n"
"    background-color: rgba(30, 30, 30, 100);\n"
"    border: none;\n"
"}\n"
"\n"
"#wtEmail, #wtPassword {\n"
"    background-color: transparent; \n"
"    border: none;\n"
"    border-bottom: 2px solid #fff;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    background-color: transparent; \n"
"    color: #fff; \n"
"    border: none;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtButton QCheckBox{\n"
"   color: #fff;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnForgotPassword{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    color: #ddd;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnForgotPassword:hover{\n"
" color: #fff;\n"
"}\n"
"\n"
"QWidget#wtButtonLoginExit QPushButton{\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    color: #000;\n"
"    background: #fff;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QWidget#wtButton QLabel#lbBottom{\n"
"    color: #fff;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnRegister{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    color: #ddd;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnRegister:hover{\n"
"    color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(LoginForm)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.wtBackground = QtWidgets.QWidget(LoginForm)
        self.wtBackground.setObjectName("wtBackground")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.wtBackground)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.wtBackgroundBlur = QtWidgets.QWidget(self.wtBackground)
        self.wtBackgroundBlur.setObjectName("wtBackgroundBlur")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wtBackgroundBlur)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wtRow1 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow1.setObjectName("wtRow1")
        self.verticalLayout_2.addWidget(self.wtRow1)
        self.wtRow2 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow2.setObjectName("wtRow2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wtRow2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wtRow2Column1 = QtWidgets.QWidget(self.wtRow2)
        self.wtRow2Column1.setObjectName("wtRow2Column1")
        self.horizontalLayout.addWidget(self.wtRow2Column1)
        self.wtForm = QtWidgets.QWidget(self.wtRow2)
        self.wtForm.setObjectName("wtForm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wtForm)
        self.verticalLayout_3.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wtTitle = QtWidgets.QWidget(self.wtForm)
        self.wtTitle.setObjectName("wtTitle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wtTitle)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.wtTitle)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.wtTitle)
        self.wtInput = QtWidgets.QWidget(self.wtForm)
        self.wtInput.setObjectName("wtInput")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wtInput)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wtEmail = QtWidgets.QWidget(self.wtInput)
        self.wtEmail.setObjectName("wtEmail")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wtEmail)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.wtEmail)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-email-24.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txtEmail = QtWidgets.QLineEdit(self.wtEmail)
        self.txtEmail.setObjectName("txtEmail")
        self.horizontalLayout_3.addWidget(self.txtEmail)
        self.verticalLayout_4.addWidget(self.wtEmail)
        self.wtPassword = QtWidgets.QWidget(self.wtInput)
        self.wtPassword.setObjectName("wtPassword")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wtPassword)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.wtPassword)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-password-24.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txtPassword = QtWidgets.QLineEdit(self.wtPassword)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout_4.addWidget(self.txtPassword)
        self.verticalLayout_4.addWidget(self.wtPassword)
        self.verticalLayout_3.addWidget(self.wtInput)
        self.wtButton = QtWidgets.QWidget(self.wtForm)
        self.wtButton.setObjectName("wtButton")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wtButton)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wtRememberMeForgotPassword = QtWidgets.QWidget(self.wtButton)
        self.wtRememberMeForgotPassword.setObjectName("wtRememberMeForgotPassword")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wtRememberMeForgotPassword)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checRememberMe = QtWidgets.QCheckBox(self.wtRememberMeForgotPassword)
        self.checRememberMe.setObjectName("checRememberMe")
        self.horizontalLayout_5.addWidget(self.checRememberMe)
        self.btnForgotPassword = QtWidgets.QPushButton(self.wtRememberMeForgotPassword)
        self.btnForgotPassword.setObjectName("btnForgotPassword")
        self.horizontalLayout_5.addWidget(self.btnForgotPassword)
        self.verticalLayout_5.addWidget(self.wtRememberMeForgotPassword)
        self.wtButtonLoginExit = QtWidgets.QWidget(self.wtButton)
        self.wtButtonLoginExit.setObjectName("wtButtonLoginExit")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.wtButtonLoginExit)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btnLogin = QtWidgets.QPushButton(self.wtButtonLoginExit)
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_6.addWidget(self.btnLogin)
        self.btnExit = QtWidgets.QPushButton(self.wtButtonLoginExit)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout_6.addWidget(self.btnExit)
        self.verticalLayout_5.addWidget(self.wtButtonLoginExit)
        self.wtNavigaToRegister = QtWidgets.QWidget(self.wtButton)
        self.wtNavigaToRegister.setObjectName("wtNavigaToRegister")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.wtNavigaToRegister)
        self.horizontalLayout_7.setContentsMargins(40, 0, 40, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbBottom = QtWidgets.QLabel(self.wtNavigaToRegister)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbBottom.sizePolicy().hasHeightForWidth())
        self.lbBottom.setSizePolicy(sizePolicy)
        self.lbBottom.setObjectName("lbBottom")
        self.horizontalLayout_7.addWidget(self.lbBottom)
        self.btnRegister = QtWidgets.QPushButton(self.wtNavigaToRegister)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRegister.sizePolicy().hasHeightForWidth())
        self.btnRegister.setSizePolicy(sizePolicy)
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout_7.addWidget(self.btnRegister)
        self.verticalLayout_5.addWidget(self.wtNavigaToRegister)
        self.verticalLayout_3.addWidget(self.wtButton)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 4)
        self.horizontalLayout.addWidget(self.wtForm)
        self.wtRow2Column3 = QtWidgets.QWidget(self.wtRow2)
        self.wtRow2Column3.setObjectName("wtRow2Column3")
        self.horizontalLayout.addWidget(self.wtRow2Column3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addWidget(self.wtRow2)
        self.wtRow3 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow3.setObjectName("wtRow3")
        self.verticalLayout_2.addWidget(self.wtRow3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 4)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_6.addWidget(self.wtBackgroundBlur)
        self.horizontalLayout_8.addWidget(self.wtBackground)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.label.setText(_translate("LoginForm", "Đăng nhập"))
        self.txtEmail.setPlaceholderText(_translate("LoginForm", "Nhập địa chỉ email"))
        self.txtPassword.setPlaceholderText(_translate("LoginForm", "Nhập mật khẩu"))
        self.checRememberMe.setText(_translate("LoginForm", "Ghi nhớ"))
        self.btnForgotPassword.setText(_translate("LoginForm", "Quên mật khẩu"))
        self.btnLogin.setText(_translate("LoginForm", "Đăng nhập"))
        self.btnExit.setText(_translate("LoginForm", "Thoát"))
        self.lbBottom.setText(_translate("LoginForm", "Bạn chưa có tài khoản?"))
        self.btnRegister.setText(_translate("LoginForm", "Đăng ký"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec_())
