# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormMain(object):
    def setupUi(self, FormMain):
        FormMain.setObjectName("FormMain")
        FormMain.resize(1366, 768)
        FormMain.setStyleSheet("/* General */\n"
"\n"
"QCheckBox {\n"
"    font: 9pt \"Comic Sans MS\";\n"
"    color: #F1F5F9;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border: none; \n"
"    background-color: #D9D9D9;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/images/icons/header/icons8-check-mark-50.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"  background-color: #E0F2FE;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    font: 9pt \"Comic Sans MS\";\n"
"    color: #F1F5F9;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    background-color: #D9D9D9;\n"
"    border-radius: 10px;\n"
"    image: url(:/images/icons/header/icons8-circle-50.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:hover {\n"
"  background-color: #E0F2FE;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    image: url(:/images/icons/header/icons8-radio-button-checked-50.png);\n"
"}\n"
"\n"
"\n"
"/* Container */\n"
"QFrame#frmContainer {\n"
"    background: #0EA5E9;\n"
"}\n"
"\n"
"/* Header */\n"
"QFrame#frmHeader {\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"/* Header Left */\n"
"QFrame#frmHeaderLeft QFrame#frmLogo {\n"
"    border-image: url(:/images/icons/header/logo.png);\n"
"    min-width: 100px;\n"
"    max-width: 100px;\n"
"}\n"
"\n"
"QFrame#frmHeaderLeft QLabel#lbSoftwareName {\n"
"    color: #F1F5F9;\n"
"    font: bold 13pt \"Times New Roman\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QFrame#frmHeaderLeft QPushButton#btnCurrentMenu {\n"
"    background: transparent;\n"
"    color: #F1F5F9;\n"
"    font: bold 9pt \"Comic Sans MS\";\n"
"    border: none;\n"
"    text-align: left;\n"
"}\n"
"\n"
"/* Header Center */\n"
"QFrame#frmHeaderCenter QPushButton#btnAccount,\n"
"QPushButton#btnProxy,\n"
"QPushButton#btnStart,\n"
"QPushButton#btnStop {\n"
"    background: #007AFF;\n"
"    font: bold 9pt \"Comic Sans MS\";\n"
"    padding: 10px;\n"
"    color: #F1F5F9;\n"
"    border: none;\n"
"    width: 110px;\n"
"}\n"
"\n"
"QFrame#frmHeaderCenter QPushButton#btnAccount:hover,\n"
"QPushButton#btnProxy:hover,\n"
"QPushButton#btnStart:hover,\n"
"QPushButton#btnStop:hover {\n"
"    background-color: #005BB5;\n"
"}\n"
"\n"
"QFrame#frmHeaderCenter QPushButton#btnAccount:disabled,\n"
"QPushButton#btnProxy:disabled,\n"
"QPushButton#btnStart:disabled,\n"
"QPushButton#btnStop:disabled {\n"
"    background-color: #D3D3D3; /* Light gray background for disabled buttons */\n"
"    color: #A9A9A9; /* Dark gray text for disabled buttons */\n"
"}\n"
"/* Header right */\n"
"\n"
"QFrame#frmHeaderRightRightTop QPushButton {\n"
"    padding: 1px;\n"
"    border: none;\n"
"    width: 20px;\n"
"    max-width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 11px;\n"
"}\n"
"\n"
"QPushButton#btnVietnamese { image: url(:/images/icons/header/vietnam.png); }\n"
"QPushButton#btnEnglish { image: url(:/images/icons/header/english.png); }\n"
"QPushButton#btnChina { image: url(:/images/icons/header/china.png); }\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005BB5;\n"
"}\n"
"\n"
"/* Window Control Buttons */\n"
"QFrame#frmHeaderRightRightTop QPushButton#btnClose,\n"
"QPushButton#btnMaximized,\n"
"QPushButton#btnMinimize {\n"
"    background: #007AFF;\n"
"}\n"
"\n"
"QFrame#frmHeaderRightRightTop QPushButton#btnClose:hover,\n"
"QPushButton#btnMaximized:hover,\n"
"QPushButton#btnMinimize:hover {\n"
"    background: #005BB5;\n"
"}\n"
"\n"
"QFrame#frmHeaderRightRightBottom QPushButton#btnShop, QPushButton#btnMessage {\n"
"   font: 9pt \"Comic Sans MS\";\n"
"   color: #F1F5F9;\n"
"   font-weight: bold;\n"
"   background: transparent;\n"
"   border-radius: 5px;\n"
"}\n"
"\n"
"QFrame#frmHeaderRightRightBottom QPushButton#btnShop:hover, QPushButton#btnMessage:hover {\n"
"   background-color: rgba(0, 0, 0, 20);\n"
"}\n"
"\n"
"/* QStackWidget  */\n"
"\n"
"QStackedWidget QPushButton {\n"
"    background: #007AFF;\n"
"    color: #F1F5F9;\n"
"    text-align: center;\n"
"    font: 10pt \"Comic Sans MS\";\n"
"    padding: 5px;\n"
"    font-weight: bold;\n"
"    margin: 0 10px;\n"
"    border: none;\n"
"}\n"
"\n"
"QStackedWidget QPushButton:hover {\n"
"    background: #005BB5;\n"
"}\n"
"\n"
"QStackedWidget#stackedWidget QWidget#pageBackground,\n"
"QWidget#pageSettings,\n"
"QWidget#pageCheckAccount,\n"
"QWidget#pageFilterMembers,\n"
"QWidget#pageFilterData,\n"
"QWidget#pageAddMember,\n"
"QWidget#pageSpamMessage,\n"
"QWidget#pageSeeding,\n"
"QWidget#pageJoinGroupChannel,\n"
"QWidget#pageLeaveGroupChannel,\n"
"QWidget#pageBuffEmotions,\n"
"QWidget#pagePostViews,\n"
"QWidget#pageChangeAccountInfor {\n"
"    background: #0EA5E9;\n"
"}\n"
"\n"
"QStackedWidget QPushButton#btnSettingsToogle,\n"
"QPushButton#btnSettingsToogleDropdown,\n"
"QPushButton#btnCheckAccountToggle,\n"
"QPushButton#btnCheckAccountToggleDropdown,\n"
"QPushButton#btnFilterMembersToggle,\n"
"QPushButton#btnFilterMembersToggleDropdown,\n"
"QPushButton#btnFilterDataToggle,\n"
"QPushButton#btnFilterDataToggleDropdown,\n"
"QPushButton#btnAddMemberToggle,\n"
"QPushButton#btnAddMemberToggleDropdown,\n"
"QPushButton#btnSpamMessageToggle,\n"
"QPushButton#btnSpamMessageToggleDropdown,\n"
"QPushButton#btnSededingToggle,\n"
"QPushButton#btnSededingToggleDropdown,\n"
"QPushButton#btnJoinGroupChannelToggle,\n"
"QPushButton#btnJoinGroupChannelToggleDropdown,\n"
"QPushButton#btnLeaveGroupChannelToggle,\n"
"QPushButton#btnLeaveGroupChannelToggleDropdown,\n"
"QPushButton#btnBuffEmotionsToggle,\n"
"QPushButton#btnBuffEmotionsToggleDropdown,\n"
"QPushButton#btnPostViewsToggle,\n"
"QPushButton#btnPostViewsToggleDropdown,\n"
"QPushButton#btnChangeAccountInforToggle,\n"
"QPushButton#btnChangeAccountInforToggleDropdown {\n"
"    background-color: rgba(0, 0, 0, 20);\n"
"    color: #F1F5F9;\n"
"    font: bold 10pt \"Comic Sans MS\";\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"    border: none;\n"
"    margin: 0;\n"
"}\n"
"\n"
"QStackedWidget QLineEdit, QTextEdit {\n"
"   background-color: #E2E8F0;\n"
"   color: #000000;\n"
"   padding: 3px;\n"
"   border: none;\n"
"   font: 10pt \"Comic Sans MS\";\n"
"   font-weight: bold;\n"
"   max-width: 30px;\n"
"   border-radius: 13px;\n"
"   border: 1px solid #005BB5;\n"
"}\n"
"\n"
"QStackedWidget#stackedWidget QLabel {\n"
"    color: #F1F5F9;\n"
"    font: 9pt \"Comic Sans MS\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Sidebar  */\n"
"\n"
"QFrame#frmSidebar QPushButton {\n"
"    background: #0EA5E9;\n"
"    color: #F1F5F9;\n"
"    font: 10pt \"Comic Sans MS\";\n"
"    padding: 10px;\n"
"    margin: 0;\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame#frmSidebar QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 20);\n"
"}\n"
"\n"
"/* pageCheckAccount  */\n"
"\n"
"QWidget#pageCheckAccount QCheckBox {\n"
"   max-width: 20px;\n"
"}\n"
"\n"
"QWidget#pageCheckAccount QLabel {\n"
"   background-color: #007AFF;\n"
"   padding: 5px;\n"
"}\n"
"\n"
"\n"
"/* Table */\n"
"\n"
"QTableWidget QHeaderView::section {\n"
"    background-color: rgba(0, 122, 255, 0.57);\n"
"    color: #F1F5F9;\n"
"    font: 11pt \"Times New Roman\";\n"
"    font-weight: bold; \n"
"    padding: 5px; \n"
"    border: none; \n"
"\n"
"}\n"
"\n"
"QTableWidget::item{\n"
"    background-color: #F1F5F9;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    color: #0F172A;\n"
"    padding-left: 5px;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #0EA5E9;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #0EA5E9; /* Match general container background */\n"
"    width: 12px;\n"
"    padding: 3px;\n"
"    margin: 42px 0 42px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #F1F5F9; /* Match light foreground elements */\n"
"    border-radius: 3px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    background: rgba(0, 122, 255, 0.57); /* Match button background */\n"
"    height: 40px;\n"
"    subcontrol-origin: margin;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    subcontrol-position: bottom;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    subcontrol-position: top;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: transparent; /* Remove arrows to match clean style */\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: none; /* Match hover/selected states with transparency */\n"
"}\n"
"\n"
"\n"
"/* Footer */\n"
"\n"
"QFrame#frmFooter QLabel {\n"
"    color: #F1F5F9;\n"
"    font-weight: bold;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QFrame#frmFooter QLabel#lbVersion {\n"
"   font: 7pt \"MS Shell Dlg 2\";\n"
"   font-weight: bold;\n"
"}\n"
"\n"
"QFrame#frmFooter QPushButton#btnCopyKey{\n"
"   background-color: transparent;\n"
"}\n"
"\n"
"#frmEmotions QCheckBox{\n"
"    font: 15pt \"Segoe UI Emoji\";\n"
"    color: #F1F5F9;\n"
"}\n"
"\n"
"")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(FormMain)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frmContainer = QtWidgets.QFrame(FormMain)
        self.frmContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmContainer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frmContainer.setObjectName("frmContainer")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frmContainer)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frmHeader = QtWidgets.QFrame(self.frmContainer)
        self.frmHeader.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frmHeader.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeader.setObjectName("frmHeader")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmHeader)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frmHeaderLeft = QtWidgets.QFrame(self.frmHeader)
        self.frmHeaderLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderLeft.setObjectName("frmHeaderLeft")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frmHeaderLeft)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frmLogo = QtWidgets.QFrame(self.frmHeaderLeft)
        self.frmLogo.setMinimumSize(QtCore.QSize(100, 0))
        self.frmLogo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frmLogo.setObjectName("frmLogo")
        self.horizontalLayout_5.addWidget(self.frmLogo)
        self.frmHeaderLeftRight = QtWidgets.QFrame(self.frmHeaderLeft)
        self.frmHeaderLeftRight.setMinimumSize(QtCore.QSize(350, 0))
        self.frmHeaderLeftRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderLeftRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderLeftRight.setObjectName("frmHeaderLeftRight")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frmHeaderLeftRight)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_37 = QtWidgets.QFrame(self.frmHeaderLeftRight)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.gridLayout_3.addWidget(self.frame_37, 1, 0, 1, 1)
        self.frmHeaderCenter = QtWidgets.QFrame(self.frmHeaderLeftRight)
        self.frmHeaderCenter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderCenter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderCenter.setObjectName("frmHeaderCenter")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frmHeaderCenter)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frmHeaderCenterButton = QtWidgets.QFrame(self.frmHeaderCenter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHeaderCenterButton.sizePolicy().hasHeightForWidth())
        self.frmHeaderCenterButton.setSizePolicy(sizePolicy)
        self.frmHeaderCenterButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHeaderCenterButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderCenterButton.setObjectName("frmHeaderCenterButton")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frmHeaderCenterButton)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnStart = QtWidgets.QPushButton(self.frmHeaderCenterButton)
        self.btnStart.setMinimumSize(QtCore.QSize(0, 0))
        self.btnStart.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_2.addWidget(self.btnStart, 1, 0, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.frmHeaderCenterButton)
        self.btnStop.setMinimumSize(QtCore.QSize(0, 0))
        self.btnStop.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_2.addWidget(self.btnStop, 1, 1, 1, 1)
        self.btnProxy = QtWidgets.QPushButton(self.frmHeaderCenterButton)
        self.btnProxy.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-add-folder-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProxy.setIcon(icon)
        self.btnProxy.setObjectName("btnProxy")
        self.gridLayout_2.addWidget(self.btnProxy, 0, 1, 1, 1)
        self.btnAccount = QtWidgets.QPushButton(self.frmHeaderCenterButton)
        self.btnAccount.setIcon(icon)
        self.btnAccount.setObjectName("btnAccount")
        self.gridLayout_2.addWidget(self.btnAccount, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frmHeaderCenterButton)
        self.frmHeaderCenterCheck = QtWidgets.QFrame(self.frmHeaderCenter)
        self.frmHeaderCenterCheck.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderCenterCheck.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderCenterCheck.setObjectName("frmHeaderCenterCheck")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frmHeaderCenterCheck)
        self.gridLayout_4.setContentsMargins(10, 0, 0, 7)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBoxProxyList = QtWidgets.QRadioButton(self.frmHeaderCenterCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxProxyList.sizePolicy().hasHeightForWidth())
        self.checkBoxProxyList.setSizePolicy(sizePolicy)
        self.checkBoxProxyList.setObjectName("checkBoxProxyList")
        self.gridLayout_4.addWidget(self.checkBoxProxyList, 0, 0, 1, 1)
        self.checkBoxProxyKey = QtWidgets.QRadioButton(self.frmHeaderCenterCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxProxyKey.sizePolicy().hasHeightForWidth())
        self.checkBoxProxyKey.setSizePolicy(sizePolicy)
        self.checkBoxProxyKey.setObjectName("checkBoxProxyKey")
        self.gridLayout_4.addWidget(self.checkBoxProxyKey, 3, 0, 1, 1)
        self.frmHTTPSock = QtWidgets.QFrame(self.frmHeaderCenterCheck)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmHTTPSock.sizePolicy().hasHeightForWidth())
        self.frmHTTPSock.setSizePolicy(sizePolicy)
        self.frmHTTPSock.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHTTPSock.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHTTPSock.setObjectName("frmHTTPSock")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frmHTTPSock)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.checkBoxHTTP = QtWidgets.QRadioButton(self.frmHTTPSock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxHTTP.sizePolicy().hasHeightForWidth())
        self.checkBoxHTTP.setSizePolicy(sizePolicy)
        self.checkBoxHTTP.setObjectName("checkBoxHTTP")
        self.horizontalLayout_34.addWidget(self.checkBoxHTTP)
        self.checkBoxSOCK = QtWidgets.QRadioButton(self.frmHTTPSock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSOCK.sizePolicy().hasHeightForWidth())
        self.checkBoxSOCK.setSizePolicy(sizePolicy)
        self.checkBoxSOCK.setObjectName("checkBoxSOCK")
        self.horizontalLayout_34.addWidget(self.checkBoxSOCK)
        self.gridLayout_4.addWidget(self.frmHTTPSock, 0, 1, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frmHeaderCenterCheck)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_4.addWidget(self.frame_36, 3, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.horizontalLayout_7.addWidget(self.frmHeaderCenterCheck)
        self.horizontalLayout_7.setStretch(0, 2)
        self.horizontalLayout_7.setStretch(1, 3)
        self.gridLayout_3.addWidget(self.frmHeaderCenter, 1, 1, 1, 1)
        self.frmSoftwareNameCurrentPage = QtWidgets.QFrame(self.frmHeaderLeftRight)
        self.frmSoftwareNameCurrentPage.setObjectName("frmSoftwareNameCurrentPage")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frmSoftwareNameCurrentPage)
        self.horizontalLayout_6.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbSoftwareName = QtWidgets.QLabel(self.frmSoftwareNameCurrentPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbSoftwareName.sizePolicy().hasHeightForWidth())
        self.lbSoftwareName.setSizePolicy(sizePolicy)
        self.lbSoftwareName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbSoftwareName.setObjectName("lbSoftwareName")
        self.horizontalLayout_6.addWidget(self.lbSoftwareName)
        self.btnCurrentMenu = QtWidgets.QPushButton(self.frmSoftwareNameCurrentPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCurrentMenu.sizePolicy().hasHeightForWidth())
        self.btnCurrentMenu.setSizePolicy(sizePolicy)
        self.btnCurrentMenu.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-home-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCurrentMenu.setIcon(icon1)
        self.btnCurrentMenu.setObjectName("btnCurrentMenu")
        self.horizontalLayout_6.addWidget(self.btnCurrentMenu)
        self.frame_38 = QtWidgets.QFrame(self.frmSoftwareNameCurrentPage)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_6.addWidget(self.frame_38)
        self.gridLayout_3.addWidget(self.frmSoftwareNameCurrentPage, 0, 0, 1, 2)
        self.gridLayout_3.setColumnStretch(0, 2)
        self.gridLayout_3.setColumnStretch(1, 6)
        self.horizontalLayout_5.addWidget(self.frmHeaderLeftRight)
        self.horizontalLayout_4.addWidget(self.frmHeaderLeft)
        self.frmHeaderRight = QtWidgets.QFrame(self.frmHeader)
        self.frmHeaderRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderRight.setObjectName("frmHeaderRight")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frmHeaderRight)
        self.horizontalLayout_8.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frmHeaderRightRight = QtWidgets.QFrame(self.frmHeaderRight)
        self.frmHeaderRightRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmHeaderRightRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderRightRight.setObjectName("frmHeaderRightRight")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmHeaderRightRight)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frmHeaderRightRightTop = QtWidgets.QFrame(self.frmHeaderRightRight)
        self.frmHeaderRightRightTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHeaderRightRightTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderRightRightTop.setObjectName("frmHeaderRightRightTop")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frmHeaderRightRightTop)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_34 = QtWidgets.QFrame(self.frmHeaderRightRightTop)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_9.addWidget(self.frame_34)
        self.btnChina = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnChina.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnChina.setText("")
        self.btnChina.setObjectName("btnChina")
        self.horizontalLayout_9.addWidget(self.btnChina)
        self.btnEnglish = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnEnglish.setText("")
        self.btnEnglish.setObjectName("btnEnglish")
        self.horizontalLayout_9.addWidget(self.btnEnglish)
        self.btnVietnamese = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnVietnamese.setText("")
        self.btnVietnamese.setObjectName("btnVietnamese")
        self.horizontalLayout_9.addWidget(self.btnVietnamese)
        self.frame_35 = QtWidgets.QFrame(self.frmHeaderRightRightTop)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_9.addWidget(self.frame_35)
        self.btnMinimize = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnMinimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/header/icons8-minimize-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimize.setIcon(icon2)
        self.btnMinimize.setIconSize(QtCore.QSize(12, 12))
        self.btnMinimize.setObjectName("btnMinimize")
        self.horizontalLayout_9.addWidget(self.btnMinimize)
        self.btnMaximized = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnMaximized.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/header/icons8-maximize-button-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMaximized.setIcon(icon3)
        self.btnMaximized.setIconSize(QtCore.QSize(12, 12))
        self.btnMaximized.setObjectName("btnMaximized")
        self.horizontalLayout_9.addWidget(self.btnMaximized)
        self.btnClose = QtWidgets.QPushButton(self.frmHeaderRightRightTop)
        self.btnClose.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/header/icons8-close-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon4)
        self.btnClose.setIconSize(QtCore.QSize(12, 12))
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_9.addWidget(self.btnClose)
        self.verticalLayout_3.addWidget(self.frmHeaderRightRightTop)
        self.frmHeaderRightRightBottom = QtWidgets.QFrame(self.frmHeaderRightRight)
        self.frmHeaderRightRightBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmHeaderRightRightBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmHeaderRightRightBottom.setObjectName("frmHeaderRightRightBottom")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frmHeaderRightRightBottom)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnMessage = QtWidgets.QPushButton(self.frmHeaderRightRightBottom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMessage.sizePolicy().hasHeightForWidth())
        self.btnMessage.setSizePolicy(sizePolicy)
        self.btnMessage.setMinimumSize(QtCore.QSize(0, 40))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/header/icons8-message-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMessage.setIcon(icon5)
        self.btnMessage.setIconSize(QtCore.QSize(30, 30))
        self.btnMessage.setObjectName("btnMessage")
        self.horizontalLayout_10.addWidget(self.btnMessage)
        self.btnShop = QtWidgets.QPushButton(self.frmHeaderRightRightBottom)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/header/icons8-shop-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShop.setIcon(icon6)
        self.btnShop.setIconSize(QtCore.QSize(40, 40))
        self.btnShop.setObjectName("btnShop")
        self.horizontalLayout_10.addWidget(self.btnShop)
        self.verticalLayout_3.addWidget(self.frmHeaderRightRightBottom)
        self.horizontalLayout_8.addWidget(self.frmHeaderRightRight)
        self.horizontalLayout_4.addWidget(self.frmHeaderRight)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout_5.addWidget(self.frmHeader)
        self.frmBody = QtWidgets.QFrame(self.frmContainer)
        self.frmBody.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBody.setLineWidth(1)
        self.frmBody.setObjectName("frmBody")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frmBody)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frmContent = QtWidgets.QFrame(self.frmBody)
        self.frmContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmContent.setObjectName("frmContent")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frmContent)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frmContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageBackground = QtWidgets.QWidget()
        self.pageBackground.setObjectName("pageBackground")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.pageBackground)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frmSidebar = QtWidgets.QFrame(self.pageBackground)
        self.frmSidebar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frmSidebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmSidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSidebar.setLineWidth(1)
        self.frmSidebar.setObjectName("frmSidebar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frmSidebar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSettings = QtWidgets.QPushButton(self.frmSidebar)
        self.btnSettings.setIcon(icon1)
        self.btnSettings.setIconSize(QtCore.QSize(30, 30))
        self.btnSettings.setObjectName("btnSettings")
        self.verticalLayout_2.addWidget(self.btnSettings)
        self.btnCheckAccount = QtWidgets.QPushButton(self.frmSidebar)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-check-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCheckAccount.setIcon(icon7)
        self.btnCheckAccount.setIconSize(QtCore.QSize(30, 30))
        self.btnCheckAccount.setObjectName("btnCheckAccount")
        self.verticalLayout_2.addWidget(self.btnCheckAccount)
        self.btnFilterMembers = QtWidgets.QPushButton(self.frmSidebar)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-scan-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterMembers.setIcon(icon8)
        self.btnFilterMembers.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterMembers.setObjectName("btnFilterMembers")
        self.verticalLayout_2.addWidget(self.btnFilterMembers)
        self.btnFilterData = QtWidgets.QPushButton(self.frmSidebar)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-phone-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFilterData.setIcon(icon9)
        self.btnFilterData.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterData.setObjectName("btnFilterData")
        self.verticalLayout_2.addWidget(self.btnFilterData)
        self.frame_3 = QtWidgets.QFrame(self.frmSidebar)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout_13.addWidget(self.frmSidebar)
        self.stackedWidget.addWidget(self.pageBackground)
        self.pageSettings = QtWidgets.QWidget()
        self.pageSettings.setObjectName("pageSettings")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.pageSettings)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frm = QtWidgets.QFrame(self.pageSettings)
        self.frm.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm.setObjectName("frm")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frm)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.btnSettingsToogle = QtWidgets.QPushButton(self.frm)
        self.btnSettingsToogle.setIcon(icon1)
        self.btnSettingsToogle.setIconSize(QtCore.QSize(30, 30))
        self.btnSettingsToogle.setObjectName("btnSettingsToogle")
        self.horizontalLayout_33.addWidget(self.btnSettingsToogle)
        self.btnSettingsToogleDropdown = QtWidgets.QPushButton(self.frm)
        self.btnSettingsToogleDropdown.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-expand-arrow-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettingsToogleDropdown.setIcon(icon10)
        self.btnSettingsToogleDropdown.setIconSize(QtCore.QSize(30, 30))
        self.btnSettingsToogleDropdown.setObjectName("btnSettingsToogleDropdown")
        self.horizontalLayout_33.addWidget(self.btnSettingsToogleDropdown)
        self.horizontalLayout_33.setStretch(0, 10)
        self.horizontalLayout_33.setStretch(1, 1)
        self.verticalLayout_31.addWidget(self.frm)
        self.frame_33 = QtWidgets.QFrame(self.pageSettings)
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_31.addWidget(self.frame_33)
        self.stackedWidget.addWidget(self.pageSettings)
        self.pageCheckAccount = QtWidgets.QWidget()
        self.pageCheckAccount.setObjectName("pageCheckAccount")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pageCheckAccount)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frmCheckAccountToggle = QtWidgets.QFrame(self.pageCheckAccount)
        self.frmCheckAccountToggle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frmCheckAccountToggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmCheckAccountToggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCheckAccountToggle.setObjectName("frmCheckAccountToggle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmCheckAccountToggle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCheckAccountToggle = QtWidgets.QPushButton(self.frmCheckAccountToggle)
        self.btnCheckAccountToggle.setIcon(icon7)
        self.btnCheckAccountToggle.setIconSize(QtCore.QSize(30, 30))
        self.btnCheckAccountToggle.setObjectName("btnCheckAccountToggle")
        self.horizontalLayout.addWidget(self.btnCheckAccountToggle)
        self.btnCheckAccountToggleDropdown = QtWidgets.QPushButton(self.frmCheckAccountToggle)
        self.btnCheckAccountToggleDropdown.setText("")
        self.btnCheckAccountToggleDropdown.setIcon(icon10)
        self.btnCheckAccountToggleDropdown.setIconSize(QtCore.QSize(30, 30))
        self.btnCheckAccountToggleDropdown.setObjectName("btnCheckAccountToggleDropdown")
        self.horizontalLayout.addWidget(self.btnCheckAccountToggleDropdown)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_7.addWidget(self.frmCheckAccountToggle)
        self.frmCheckAccount = QtWidgets.QFrame(self.pageCheckAccount)
        self.frmCheckAccount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmCheckAccount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmCheckAccount.setObjectName("frmCheckAccount")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frmCheckAccount)
        self.verticalLayout_6.setContentsMargins(-1, 50, -1, 300)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.frmCheckAccount)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxCheckLive = QtWidgets.QRadioButton(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCheckLive.sizePolicy().hasHeightForWidth())
        self.checkBoxCheckLive.setSizePolicy(sizePolicy)
        self.checkBoxCheckLive.setText("")
        self.checkBoxCheckLive.setChecked(True)
        self.checkBoxCheckLive.setObjectName("checkBoxCheckLive")
        self.gridLayout.addWidget(self.checkBoxCheckLive, 0, 0, 1, 1)
        self.checkBoxCheckSpam = QtWidgets.QRadioButton(self.frame_12)
        self.checkBoxCheckSpam.setText("")
        self.checkBoxCheckSpam.setObjectName("checkBoxCheckSpam")
        self.gridLayout.addWidget(self.checkBoxCheckSpam, 1, 0, 1, 1)
        self.lbCheckBoxCheckSpam = QtWidgets.QLabel(self.frame_12)
        self.lbCheckBoxCheckSpam.setObjectName("lbCheckBoxCheckSpam")
        self.gridLayout.addWidget(self.lbCheckBoxCheckSpam, 0, 1, 1, 1)
        self.lbcheckBoxCheckLive = QtWidgets.QLabel(self.frame_12)
        self.lbcheckBoxCheckLive.setObjectName("lbcheckBoxCheckLive")
        self.gridLayout.addWidget(self.lbcheckBoxCheckLive, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.verticalLayout_7.addWidget(self.frmCheckAccount)
        self.stackedWidget.addWidget(self.pageCheckAccount)
        self.pageFilterMembers = QtWidgets.QWidget()
        self.pageFilterMembers.setObjectName("pageFilterMembers")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageFilterMembers)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame = QtWidgets.QFrame(self.pageFilterMembers)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btnFilterMembersToggle = QtWidgets.QPushButton(self.frame)
        self.btnFilterMembersToggle.setIcon(icon8)
        self.btnFilterMembersToggle.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterMembersToggle.setObjectName("btnFilterMembersToggle")
        self.horizontalLayout_23.addWidget(self.btnFilterMembersToggle)
        self.btnFilterMembersToggleDropdown = QtWidgets.QPushButton(self.frame)
        self.btnFilterMembersToggleDropdown.setText("")
        self.btnFilterMembersToggleDropdown.setIcon(icon10)
        self.btnFilterMembersToggleDropdown.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterMembersToggleDropdown.setObjectName("btnFilterMembersToggleDropdown")
        self.horizontalLayout_23.addWidget(self.btnFilterMembersToggleDropdown)
        self.horizontalLayout_23.setStretch(0, 10)
        self.horizontalLayout_23.setStretch(1, 1)
        self.verticalLayout_8.addWidget(self.frame)
        self.frame_9 = QtWidgets.QFrame(self.pageFilterMembers)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setContentsMargins(-1, 50, -1, 50)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.txtFilterMembersLinkGroupNeedFilter = QtWidgets.QLineEdit(self.frame_9)
        self.txtFilterMembersLinkGroupNeedFilter.setStyleSheet("max-width: 9999;")
        self.txtFilterMembersLinkGroupNeedFilter.setObjectName("txtFilterMembersLinkGroupNeedFilter")
        self.verticalLayout_9.addWidget(self.txtFilterMembersLinkGroupNeedFilter)
        self.checkBoxFilterGroupHideMember = QtWidgets.QCheckBox(self.frame_9)
        self.checkBoxFilterGroupHideMember.setChecked(False)
        self.checkBoxFilterGroupHideMember.setObjectName("checkBoxFilterGroupHideMember")
        self.verticalLayout_9.addWidget(self.checkBoxFilterGroupHideMember)
        self.checkBoxFilterGroupHideMemberViet = QtWidgets.QCheckBox(self.frame_9)
        self.checkBoxFilterGroupHideMemberViet.setChecked(False)
        self.checkBoxFilterGroupHideMemberViet.setObjectName("checkBoxFilterGroupHideMemberViet")
        self.verticalLayout_9.addWidget(self.checkBoxFilterGroupHideMemberViet)
        self.checkBoxMemberOnline = QtWidgets.QCheckBox(self.frame_9)
        self.checkBoxMemberOnline.setChecked(False)
        self.checkBoxMemberOnline.setObjectName("checkBoxMemberOnline")
        self.verticalLayout_9.addWidget(self.checkBoxMemberOnline)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frame_8 = QtWidgets.QFrame(self.pageFilterMembers)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 180)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lbNumberDateNeedFilter = QtWidgets.QLabel(self.frame_13)
        self.lbNumberDateNeedFilter.setObjectName("lbNumberDateNeedFilter")
        self.horizontalLayout_12.addWidget(self.lbNumberDateNeedFilter)
        self.txtNumberDateNeedFilter = QtWidgets.QLineEdit(self.frame_13)
        self.txtNumberDateNeedFilter.setObjectName("txtNumberDateNeedFilter")
        self.horizontalLayout_12.addWidget(self.txtNumberDateNeedFilter)
        self.verticalLayout_10.addWidget(self.frame_13)
        self.btnSaveFileMember = QtWidgets.QPushButton(self.frame_8)
        self.btnSaveFileMember.setObjectName("btnSaveFileMember")
        self.verticalLayout_10.addWidget(self.btnSaveFileMember)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.pageFilterMembers)
        self.pageFilterData = QtWidgets.QWidget()
        self.pageFilterData.setObjectName("pageFilterData")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pageFilterData)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.pageFilterData)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btnFilterDataToggle = QtWidgets.QPushButton(self.frame_2)
        self.btnFilterDataToggle.setIcon(icon9)
        self.btnFilterDataToggle.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterDataToggle.setObjectName("btnFilterDataToggle")
        self.horizontalLayout_24.addWidget(self.btnFilterDataToggle)
        self.btnFilterDataToggleDropdown = QtWidgets.QPushButton(self.frame_2)
        self.btnFilterDataToggleDropdown.setText("")
        self.btnFilterDataToggleDropdown.setIcon(icon10)
        self.btnFilterDataToggleDropdown.setIconSize(QtCore.QSize(30, 30))
        self.btnFilterDataToggleDropdown.setObjectName("btnFilterDataToggleDropdown")
        self.horizontalLayout_24.addWidget(self.btnFilterDataToggleDropdown)
        self.horizontalLayout_24.setStretch(0, 10)
        self.horizontalLayout_24.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.frame_11 = QtWidgets.QFrame(self.pageFilterData)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_13.setContentsMargins(-1, 20, -1, 250)
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.btnFileDataSDT = QtWidgets.QPushButton(self.frame_11)
        self.btnFileDataSDT.setObjectName("btnFileDataSDT")
        self.verticalLayout_13.addWidget(self.btnFileDataSDT)
        self.lbQuantityPhoneNumberNeedFilter = QtWidgets.QLabel(self.frame_11)
        self.lbQuantityPhoneNumberNeedFilter.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbQuantityPhoneNumberNeedFilter.setWordWrap(True)
        self.lbQuantityPhoneNumberNeedFilter.setObjectName("lbQuantityPhoneNumberNeedFilter")
        self.verticalLayout_13.addWidget(self.lbQuantityPhoneNumberNeedFilter)
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_15.setContentsMargins(20, 4, 20, 4)
        self.horizontalLayout_15.setSpacing(15)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.txtFilterDatSDTAccount = QtWidgets.QLineEdit(self.frame_15)
        self.txtFilterDatSDTAccount.setObjectName("txtFilterDatSDTAccount")
        self.horizontalLayout_15.addWidget(self.txtFilterDatSDTAccount)
        self.lbPhoneAccount = QtWidgets.QLabel(self.frame_15)
        self.lbPhoneAccount.setObjectName("lbPhoneAccount")
        self.horizontalLayout_15.addWidget(self.lbPhoneAccount)
        self.verticalLayout_13.addWidget(self.frame_15)
        self.btnSaveFileHadFilter = QtWidgets.QPushButton(self.frame_11)
        self.btnSaveFileHadFilter.setObjectName("btnSaveFileHadFilter")
        self.verticalLayout_13.addWidget(self.btnSaveFileHadFilter)
        self.verticalLayout_11.addWidget(self.frame_11)
        self.stackedWidget.addWidget(self.pageFilterData)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.tableWidget = QtWidgets.QTableWidget(self.frmContent)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(31)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_11.addWidget(self.tableWidget)
        self.horizontalLayout_11.setStretch(1, 3)
        self.horizontalLayout_2.addWidget(self.frmContent)
        self.verticalLayout_5.addWidget(self.frmBody)
        self.frmFooter = QtWidgets.QFrame(self.frmContainer)
        self.frmFooter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frmFooter.setObjectName("frmFooter")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmFooter)
        self.horizontalLayout_3.setContentsMargins(30, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbVersion = QtWidgets.QLabel(self.frmFooter)
        self.lbVersion.setObjectName("lbVersion")
        self.horizontalLayout_3.addWidget(self.lbVersion)
        spacerItem = QtWidgets.QSpacerItem(590, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnCopyKey = QtWidgets.QPushButton(self.frmFooter)
        self.btnCopyKey.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/icons/sidebar/icons8-copy-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopyKey.setIcon(icon11)
        self.btnCopyKey.setObjectName("btnCopyKey")
        self.horizontalLayout_3.addWidget(self.btnCopyKey)
        self.lbKeyText = QtWidgets.QLabel(self.frmFooter)
        self.lbKeyText.setObjectName("lbKeyText")
        self.horizontalLayout_3.addWidget(self.lbKeyText)
        self.lbKey = QtWidgets.QLabel(self.frmFooter)
        self.lbKey.setObjectName("lbKey")
        self.horizontalLayout_3.addWidget(self.lbKey)
        self.lbTextExpiration = QtWidgets.QLabel(self.frmFooter)
        self.lbTextExpiration.setObjectName("lbTextExpiration")
        self.horizontalLayout_3.addWidget(self.lbTextExpiration)
        self.lbExpirationDate = QtWidgets.QLabel(self.frmFooter)
        self.lbExpirationDate.setObjectName("lbExpirationDate")
        self.horizontalLayout_3.addWidget(self.lbExpirationDate)
        self.verticalLayout_5.addWidget(self.frmFooter)
        self.verticalLayout_30.addWidget(self.frmContainer)

        self.retranslateUi(FormMain)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(FormMain)

    def retranslateUi(self, FormMain):
        _translate = QtCore.QCoreApplication.translate
        FormMain.setWindowTitle(_translate("FormMain", "Form"))
        self.btnStart.setText(_translate("FormMain", "BẮT ĐẦU"))
        self.btnStop.setText(_translate("FormMain", "DỪNG"))
        self.btnProxy.setText(_translate("FormMain", "PROXY"))
        self.btnAccount.setText(_translate("FormMain", "TÀI KHOẢN"))
        self.checkBoxProxyList.setText(_translate("FormMain", "Proxy list"))
        self.checkBoxProxyKey.setText(_translate("FormMain", "Proxy Key(khuyên dùng)"))
        self.checkBoxHTTP.setText(_translate("FormMain", "Http"))
        self.checkBoxSOCK.setText(_translate("FormMain", "Sock"))
        self.lbSoftwareName.setText(_translate("FormMain", "KOS SOFTWARE"))
        self.btnCurrentMenu.setText(_translate("FormMain", "CÀI ĐẶT"))
        self.btnMessage.setText(_translate("FormMain", "Tin nhắn"))
        self.btnShop.setText(_translate("FormMain", "Shop Tài Khoản"))
        self.btnSettings.setText(_translate("FormMain", "CÀI ĐẶT"))
        self.btnCheckAccount.setText(_translate("FormMain", "Check Tài Khoản"))
        self.btnFilterMembers.setText(_translate("FormMain", "Lọc Thành Viên"))
        self.btnFilterData.setText(_translate("FormMain", "Lọc Data SĐT"))
        self.btnSettingsToogle.setText(_translate("FormMain", "CÀI ĐẶT"))
        self.btnCheckAccountToggle.setText(_translate("FormMain", "Check Tài Khoản"))
        self.lbCheckBoxCheckSpam.setText(_translate("FormMain", "CHECK LIVE"))
        self.lbcheckBoxCheckLive.setText(_translate("FormMain", "CHECK SPAM"))
        self.btnFilterMembersToggle.setText(_translate("FormMain", "Lọc Thành Viên"))
        self.txtFilterMembersLinkGroupNeedFilter.setPlaceholderText(_translate("FormMain", "link nhóm cần lọc"))
        self.checkBoxFilterGroupHideMember.setText(_translate("FormMain", "Lọc Nhóm ẩn Member "))
        self.checkBoxFilterGroupHideMemberViet.setText(_translate("FormMain", "Lọc Lấy Member Việt"))
        self.checkBoxMemberOnline.setText(_translate("FormMain", "Member Online"))
        self.lbNumberDateNeedFilter.setText(_translate("FormMain", "Số Ngày Cần Lọc"))
        self.txtNumberDateNeedFilter.setText(_translate("FormMain", "1"))
        self.btnSaveFileMember.setText(_translate("FormMain", "Lưu File Member"))
        self.btnFilterDataToggle.setText(_translate("FormMain", "Lọc Data SĐT"))
        self.btnFileDataSDT.setText(_translate("FormMain", "Tệp DATA SDT"))
        self.lbQuantityPhoneNumberNeedFilter.setText(_translate("FormMain", "Số lượng SDT  cần lọc trên  mỗi tài khoản Telgram"))
        self.txtFilterDatSDTAccount.setText(_translate("FormMain", "10"))
        self.lbPhoneAccount.setText(_translate("FormMain", "SDT/tài khoản"))
        self.btnSaveFileHadFilter.setText(_translate("FormMain", "Lưu File Đã lọc"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(16)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(17)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(18)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(19)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(20)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(21)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(22)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(23)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(24)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(25)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(26)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(27)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(28)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(29)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.verticalHeaderItem(30)
        item.setText(_translate("FormMain", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormMain", "TÀI KHOẢN"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormMain", "PROXY"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormMain", "KẾT QUẢ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FormMain", "STATUS"))
        self.lbVersion.setText(_translate("FormMain", "BY KOS SOFTWARE V1.1"))
        self.lbKeyText.setText(_translate("FormMain", "KEY:"))
        self.lbKey.setText(_translate("FormMain", "ASKDBJKASDNLANKL KLASLDKNASKLD"))
        self.lbTextExpiration.setText(_translate("FormMain", "  Ngày hết hạn:"))
        self.lbExpirationDate.setText(_translate("FormMain", "  01.01.2025"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMain = QtWidgets.QWidget()
    ui = Ui_FormMain()
    ui.setupUi(FormMain)
    FormMain.show()
    sys.exit(app.exec_())
