# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_payment(object):
    def setupUi(self, payment):
        payment.setObjectName("payment")
        payment.resize(796, 545)
        payment.setStyleSheet("QWidget#payment {\n"
"background-color: #E0F2FE;\n"
"}\n"
"QFrame#frmLeft {\n"
"        border-image: url(:/images/icons/start/logo_start.png);\n"
"}\n"
"\n"
"QFrame#frmQR {\n"
"        border-image: url(:/images/icons/start/image 3.png);\n"
"}\n"
"QPushButton#btnCopy {\n"
"max-width: 80px;\n"
"font: 10pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: #D9D9D9;\n"
"padding: 6px 10px;\n"
"}\n"
"QLabel#lbKey {\n"
"background-color: #14AE5C;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 0 10px;\n"
"border: none;\n"
"}\n"
"QLabel#lbKey {\n"
"background-color: #14AE5C;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 0 10px;\n"
"border: none;\n"
"}\n"
"\n"
"QFrame#frmListPrice QLabel#lbDonePayment{\n"
"   background-color: #7AF1FF;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 5px;\n"
"qproperty-alignment: \'AlignVCenter | AlignHCenter\';\n"
"}\n"
"QFrame#frmGenerateQR {\n"
"   background-color: #D9D9D9;\n"
"}\n"
"")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(payment)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frmTop = QtWidgets.QFrame(payment)
        self.frmTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTop.setObjectName("frmTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmTop)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmLeft = QtWidgets.QFrame(self.frmTop)
        self.frmLeft.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frmLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLeft.setObjectName("frmLeft")
        self.horizontalLayout.addWidget(self.frmLeft)
        self.frmQR = QtWidgets.QFrame(self.frmTop)
        self.frmQR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmQR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmQR.setObjectName("frmQR")
        self.horizontalLayout.addWidget(self.frmQR)
        self.verticalLayout_4.addWidget(self.frmTop)
        self.frmButtom = QtWidgets.QFrame(payment)
        self.frmButtom.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frmButtom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmButtom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmButtom.setObjectName("frmButtom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frmButtom)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frmRight = QtWidgets.QFrame(self.frmButtom)
        self.frmRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmRight.setObjectName("frmRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmRight)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frmRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frmRight)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbKey = QtWidgets.QLabel(self.frame_3)
        self.lbKey.setObjectName("lbKey")
        self.horizontalLayout_2.addWidget(self.lbKey)
        self.btnCopy = QtWidgets.QPushButton(self.frame_3)
        self.btnCopy.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/start/Copy Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopy.setIcon(icon)
        self.btnCopy.setObjectName("btnCopy")
        self.horizontalLayout_2.addWidget(self.btnCopy)
        self.verticalLayout.addWidget(self.frame_3)
        self.frmListPrice = QtWidgets.QFrame(self.frmRight)
        self.frmListPrice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmListPrice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmListPrice.setObjectName("frmListPrice")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmListPrice)
        self.verticalLayout_3.setContentsMargins(70, 0, 70, 30)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbDonePayment = QtWidgets.QLabel(self.frmListPrice)
        self.lbDonePayment.setMinimumSize(QtCore.QSize(0, 30))
        self.lbDonePayment.setWordWrap(False)
        self.lbDonePayment.setObjectName("lbDonePayment")
        self.verticalLayout_3.addWidget(self.lbDonePayment)
        self.verticalLayout.addWidget(self.frmListPrice)
        self.label_2 = QtWidgets.QLabel(self.frmRight)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4.addWidget(self.frmRight)
        self.frmGenerateQR = QtWidgets.QFrame(self.frmButtom)
        self.frmGenerateQR.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmGenerateQR.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmGenerateQR.setObjectName("frmGenerateQR")
        self.horizontalLayout_4.addWidget(self.frmGenerateQR)
        self.verticalLayout_4.addWidget(self.frmButtom)

        self.retranslateUi(payment)
        QtCore.QMetaObject.connectSlotsByName(payment)

    def retranslateUi(self, payment):
        _translate = QtCore.QCoreApplication.translate
        payment.setWindowTitle(_translate("payment", "Form"))
        self.label.setText(_translate("payment", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ff2d55;\">KEY KÍCH HOẠT</span></p></body></html>"))
        self.lbKey.setText(_translate("payment", "asdasdasdasdasdasdas "))
        self.btnCopy.setText(_translate("payment", "COPY"))
        self.lbDonePayment.setText(_translate("payment", "ĐÃ CHUYỂN KHOẢN"))
        self.label_2.setText(_translate("payment", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#007aff;\">lưu ý: chú ý chuyển khoản đúng nội dung bắt</span></p><p><span style=\" font-size:10pt; font-weight:600; color:#007aff;\">buộc.quét Qr để chuyển khoản đúng nội dung.</span></p></body></html>"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    payment = QtWidgets.QWidget()
    ui = Ui_payment()
    ui.setupUi(payment)
    payment.show()
    sys.exit(app.exec_())
