# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(900, 600)
        RegisterForm.setStyleSheet("QWidget#wtTitle QLabel {\n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"    color: #fff; \n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtBackground {\n"
"    border-image: url(:/images/icons/login/119254-abstract-bright-blue-background-graphic-design.jpg);\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QWidget#wtBackgroundBlur {\n"
"   background-color: rgba(30, 30, 30, 50);\n"
"}\n"
"\n"
"QWidget#wtForm {\n"
"    border-radius: 16px;\n"
"    background-color: rgba(30, 30, 30, 100);\n"
"}\n"
"\n"
"#wtEmail, #wtPassword, #wtUsername, #wtConfirmPassword {\n"
"    background-color: transparent; \n"
"    border: none;\n"
"    border-bottom: 2px solid #fff;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding: 5px;\n"
"    background-color: transparent; \n"
"    color: #fff; \n"
"    border: none;\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtRegisterExit QPushButton{\n"
"    font: 11pt \"MS Shell Dlg 2\";\n"
"    color: #000;\n"
"    background: #fff;\n"
"    border: none;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QWidget#wtButton QLabel#lbBottom{\n"
"    color: #fff;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnLogin{\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    color: #ddd;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget#wtButton QPushButton#btnLogin:hover{\n"
"    color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(RegisterForm)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.wtBackground = QtWidgets.QWidget(RegisterForm)
        self.wtBackground.setObjectName("wtBackground")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.wtBackground)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wtBackgroundBlur = QtWidgets.QWidget(self.wtBackground)
        self.wtBackgroundBlur.setObjectName("wtBackgroundBlur")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wtBackgroundBlur)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wtRow1 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow1.setObjectName("wtRow1")
        self.verticalLayout_2.addWidget(self.wtRow1)
        self.wtRow2 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow2.setObjectName("wtRow2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wtRow2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wtRow2Column1 = QtWidgets.QWidget(self.wtRow2)
        self.wtRow2Column1.setObjectName("wtRow2Column1")
        self.horizontalLayout.addWidget(self.wtRow2Column1)
        self.wtForm = QtWidgets.QWidget(self.wtRow2)
        self.wtForm.setObjectName("wtForm")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wtForm)
        self.verticalLayout_3.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wtTitle = QtWidgets.QWidget(self.wtForm)
        self.wtTitle.setObjectName("wtTitle")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wtTitle)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.wtTitle)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.wtTitle)
        self.wtInput = QtWidgets.QWidget(self.wtForm)
        self.wtInput.setObjectName("wtInput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wtInput)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wtUsername = QtWidgets.QWidget(self.wtInput)
        self.wtUsername.setObjectName("wtUsername")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wtUsername)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.wtUsername)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-email-24.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txtEmail = QtWidgets.QLineEdit(self.wtUsername)
        self.txtEmail.setObjectName("txtEmail")
        self.horizontalLayout_3.addWidget(self.txtEmail)
        self.verticalLayout.addWidget(self.wtUsername)
        self.wtEmail = QtWidgets.QWidget(self.wtInput)
        self.wtEmail.setObjectName("wtEmail")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.wtEmail)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.wtEmail)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-user-24.png"))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.txtUsername = QtWidgets.QLineEdit(self.wtEmail)
        self.txtUsername.setText("")
        self.txtUsername.setObjectName("txtUsername")
        self.horizontalLayout_9.addWidget(self.txtUsername)
        self.verticalLayout.addWidget(self.wtEmail)
        self.wtPassword = QtWidgets.QWidget(self.wtInput)
        self.wtPassword.setObjectName("wtPassword")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.wtPassword)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.wtPassword)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-password-24.png"))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txtPassword = QtWidgets.QLineEdit(self.wtPassword)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.horizontalLayout_4.addWidget(self.txtPassword)
        self.verticalLayout.addWidget(self.wtPassword)
        self.wtConfirmPassword = QtWidgets.QWidget(self.wtInput)
        self.wtConfirmPassword.setObjectName("wtConfirmPassword")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.wtConfirmPassword)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.wtConfirmPassword)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/images/icons/login/icons8-password-24.png"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.txtConfirmPassword = QtWidgets.QLineEdit(self.wtConfirmPassword)
        self.txtConfirmPassword.setText("")
        self.txtConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtConfirmPassword.setObjectName("txtConfirmPassword")
        self.horizontalLayout_10.addWidget(self.txtConfirmPassword)
        self.verticalLayout.addWidget(self.wtConfirmPassword)
        self.verticalLayout_3.addWidget(self.wtInput)
        self.wtButton = QtWidgets.QWidget(self.wtForm)
        self.wtButton.setObjectName("wtButton")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.wtButton)
        self.verticalLayout_5.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wtRegisterExit = QtWidgets.QWidget(self.wtButton)
        self.wtRegisterExit.setObjectName("wtRegisterExit")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wtRegisterExit)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnRegister = QtWidgets.QPushButton(self.wtRegisterExit)
        self.btnRegister.setObjectName("btnRegister")
        self.verticalLayout_4.addWidget(self.btnRegister)
        self.btnExit = QtWidgets.QPushButton(self.wtRegisterExit)
        self.btnExit.setObjectName("btnExit")
        self.verticalLayout_4.addWidget(self.btnExit)
        self.verticalLayout_5.addWidget(self.wtRegisterExit)
        self.widget_3 = QtWidgets.QWidget(self.wtButton)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_7.setContentsMargins(40, 0, 40, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbBottom = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbBottom.sizePolicy().hasHeightForWidth())
        self.lbBottom.setSizePolicy(sizePolicy)
        self.lbBottom.setObjectName("lbBottom")
        self.horizontalLayout_7.addWidget(self.lbBottom)
        self.btnLogin = QtWidgets.QPushButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLogin.sizePolicy().hasHeightForWidth())
        self.btnLogin.setSizePolicy(sizePolicy)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout_7.addWidget(self.btnLogin)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.wtButton)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(1, 5)
        self.verticalLayout_3.setStretch(2, 3)
        self.horizontalLayout.addWidget(self.wtForm)
        self.wtRow2Column3 = QtWidgets.QWidget(self.wtRow2)
        self.wtRow2Column3.setObjectName("wtRow2Column3")
        self.horizontalLayout.addWidget(self.wtRow2Column3)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_2.addWidget(self.wtRow2)
        self.wtRow3 = QtWidgets.QWidget(self.wtBackgroundBlur)
        self.wtRow3.setObjectName("wtRow3")
        self.verticalLayout_2.addWidget(self.wtRow3)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 6)
        self.verticalLayout_2.setStretch(2, 1)
        self.horizontalLayout_5.addWidget(self.wtBackgroundBlur)
        self.horizontalLayout_6.addWidget(self.wtBackground)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Form"))
        self.label.setText(_translate("RegisterForm", "Đăng ký"))
        self.txtEmail.setPlaceholderText(_translate("RegisterForm", "Nhập địa chỉ email"))
        self.txtUsername.setPlaceholderText(_translate("RegisterForm", "Nhập tên người dùng"))
        self.txtPassword.setPlaceholderText(_translate("RegisterForm", "Nhập mật khẩu"))
        self.txtConfirmPassword.setToolTip(_translate("RegisterForm", "<html><head/><body><p><br/></p></body></html>"))
        self.txtConfirmPassword.setPlaceholderText(_translate("RegisterForm", "Nhập lại mật khẩu"))
        self.btnRegister.setText(_translate("RegisterForm", "Đăng ký"))
        self.btnExit.setText(_translate("RegisterForm", "Thoát"))
        self.lbBottom.setText(_translate("RegisterForm", "Bạn đã có tài khoản?"))
        self.btnLogin.setText(_translate("RegisterForm", "Đăng nhập"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterForm = QtWidgets.QWidget()
    ui = Ui_RegisterForm()
    ui.setupUi(RegisterForm)
    RegisterForm.show()
    sys.exit(app.exec_())
