# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_start(object):
    def setupUi(self, start):
        start.setObjectName("start")
        start.resize(710, 255)
        start.setStyleSheet("QWidget#start {\n"
"background-color: #E0F2FE;\n"
"}\n"
"QFrame#frmLeft {\n"
"        border-image: url(:/images/icons/start/logo_start.png);\n"
"}\n"
"QPushButton#btnCopy {\n"
"max-width: 80px;\n"
"font: 10pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"border: none;\n"
"background-color: #D9D9D9;\n"
"padding: 6px 10px;\n"
"}\n"
"QLabel#lbKey {\n"
"background-color: #14AE5C;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 0 10px;\n"
"border: none;\n"
"}\n"
"QLabel#lbKey {\n"
"background-color: #14AE5C;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 0 10px;\n"
"border: none;\n"
"}\n"
"QFrame#frmSocialLink QPushButton{\n"
"border: none;\n"
"background-color: transparent;\n"
"}\n"
"QFrame#frmListPrice QLabel{\n"
"   background-color: #7AF1FF;\n"
"font: 12pt \"Times New Roman\";\n"
"font-weight: bold;\n"
"padding: 5px;\n"
"qproperty-alignment: \'AlignVCenter | AlignHCenter\';\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(start)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frmLeft = QtWidgets.QFrame(start)
        self.frmLeft.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frmLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmLeft.setObjectName("frmLeft")
        self.horizontalLayout.addWidget(self.frmLeft)
        self.frmRight = QtWidgets.QFrame(start)
        self.frmRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frmRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmRight.setObjectName("frmRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frmRight)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.frmRight)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frmRight)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbKey = QtWidgets.QLabel(self.frame_3)
        self.lbKey.setObjectName("lbKey")
        self.horizontalLayout_2.addWidget(self.lbKey)
        self.btnCopy = QtWidgets.QPushButton(self.frame_3)
        self.btnCopy.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/start/Copy Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopy.setIcon(icon)
        self.btnCopy.setObjectName("btnCopy")
        self.horizontalLayout_2.addWidget(self.btnCopy)
        self.verticalLayout.addWidget(self.frame_3)
        self.frmSocialLink = QtWidgets.QFrame(self.frmRight)
        self.frmSocialLink.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmSocialLink.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmSocialLink.setObjectName("frmSocialLink")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frmSocialLink)
        self.horizontalLayout_3.setContentsMargins(30, -1, 30, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frmSocialLink)
        self.pushButton_5.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/start/Send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton = QtWidgets.QPushButton(self.frmSocialLink)
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/start/Youtube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frmSocialLink)
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/start/Facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frmSocialLink)
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/start/Web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frmSocialLink)
        self.pushButton_4.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/start/Store 2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frmSocialLink)
        self.frmListPrice = QtWidgets.QFrame(self.frmRight)
        self.frmListPrice.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmListPrice.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmListPrice.setObjectName("frmListPrice")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frmListPrice)
        self.verticalLayout_3.setContentsMargins(70, 0, 70, 0)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frmListPrice)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frmListPrice)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frmListPrice)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.frmListPrice)
        self.horizontalLayout.addWidget(self.frmRight)

        self.retranslateUi(start)
        QtCore.QMetaObject.connectSlotsByName(start)

    def retranslateUi(self, start):
        _translate = QtCore.QCoreApplication.translate
        start.setWindowTitle(_translate("start", "Form"))
        self.label.setText(_translate("start", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ff2d55;\">KEY KÍCH HOẠT</span></p></body></html>"))
        self.lbKey.setText(_translate("start", "asdasdasdasdasdasdas "))
        self.btnCopy.setText(_translate("start", "COPY"))
        self.label_2.setText(_translate("start", "<html><head/><body><p><span style=\" font-size:12pt;\">1 Tháng: 1.000.000đ</span></p></body></html>"))
        self.label_3.setText(_translate("start", "<html><head/><body><p><span style=\" font-size:12pt;\">1 Năm: 3.000.000đ</span></p></body></html>"))
        self.label_4.setText(_translate("start", "<html><head/><body><p><span style=\" font-size:12pt;\">Vĩnh Viễn: 5.000.000đ</span></p></body></html>"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    start = QtWidgets.QWidget()
    ui = Ui_start()
    ui.setupUi(start)
    start.show()
    sys.exit(app.exec_())
